export const CM_THEME_LIST: { id: string; label: string }[] = [
  { id: 'github-light',    label: 'GitHub Light' },
  { id: 'github-dark',     label: 'GitHub Dark' },
  { id: 'material-light',  label: 'Material Light' },
  { id: 'material-dark',   label: 'Material Dark' },
  { id: 'nord',            label: 'Nord' },
  { id: 'dracula',         label: 'Dracula' },
  { id: 'xcode-light',     label: 'Xcode Light' },
  { id: 'xcode-dark',      label: 'Xcode Dark' },
  { id: 'monokai',         label: 'Monokai' },
  { id: 'solarized-light', label: 'Solarized Light' },
  { id: 'solarized-dark',  label: 'Solarized Dark' },
  { id: 'bbedit',          label: 'BBEdit' },
  { id: 'aura',            label: 'Aura' },
  { id: 'sublime',         label: 'Sublime' },
  { id: 'duotone-light',   label: 'Duotone Light' },
  { id: 'duotone-dark',    label: 'Duotone Dark' },
  { id: 'tokyo-night',     label: 'Tokyo Night' },
  { id: 'andromeda',       label: 'Andromeda' },
  { id: 'atomone',         label: 'Atom One Dark' },
  { id: 'okaidia',         label: 'Okaidia' },
  { id: 'copilot',         label: 'Copilot' },
  { id: 'eclipse',         label: 'Eclipse' },
  { id: 'basic-light',     label: 'Basic Light' },
  { id: 'basic-dark',      label: 'Basic Dark' },
  { id: 'white-light',     label: 'White Light' },
  { id: 'white-dark',      label: 'White Dark' },
  { id: 'catppuccin-latte',     label: 'Catppuccin Latte' },
  { id: 'catppuccin-frappe',    label: 'Catppuccin Frappé' },
  { id: 'catppuccin-macchiato', label: 'Catppuccin Macchiato' },
  { id: 'catppuccin-mocha',     label: 'Catppuccin Mocha' },
];
