// Prism themes offered for preview code blocks: a curated subset of prismjs
// built-ins + the prism-themes community pack + vendored Catppuccin flavors.
// To remove a theme, delete its line here AND its import+map entry in
// prism-theme.ts (both files must stay in sync).
export const PRISM_THEME_LIST: { id: string; label: string }[] = [
  { id: 'default', label: 'Default' },
  { id: 'okaidia', label: 'Okaidia' },
  { id: 'twilight', label: 'Twilight' },
  { id: 'solarizedlight', label: 'Solarized Light' },
  { id: 'tomorrow', label: 'Tomorrow' },
  { id: 'a11y-dark', label: 'A11y Dark' },
  { id: 'atom-dark', label: 'Atom Dark' },
  { id: 'base16-ateliersulphurpool.light', label: 'Base16 Ateliersulphurpool Light' },
  { id: 'cb', label: 'Cb' },
  { id: 'coldark-cold', label: 'Coldark Cold' },
  { id: 'coldark-dark', label: 'Coldark Dark' },
  { id: 'coy-without-shadows', label: 'Coy Without Shadows' },
  { id: 'darcula', label: 'Darcula' },
  { id: 'dracula', label: 'Dracula' },
  { id: 'duotone-dark', label: 'Duotone Dark' },
  { id: 'duotone-earth', label: 'Duotone Earth' },
  { id: 'duotone-forest', label: 'Duotone Forest' },
  { id: 'duotone-light', label: 'Duotone Light' },
  { id: 'duotone-sea', label: 'Duotone Sea' },
  { id: 'duotone-space', label: 'Duotone Space' },
  { id: 'ghcolors', label: 'Ghcolors' },
  { id: 'gruvbox-dark', label: 'Gruvbox Dark' },
  { id: 'gruvbox-light', label: 'Gruvbox Light' },
  { id: 'holi-theme', label: 'Holi Theme' },
  { id: 'hopscotch', label: 'Hopscotch' },
  { id: 'lucario', label: 'Lucario' },
  { id: 'material-dark', label: 'Material Dark' },
  { id: 'material-light', label: 'Material Light' },
  { id: 'material-oceanic', label: 'Material Oceanic' },
  { id: 'night-owl', label: 'Night Owl' },
  { id: 'nord', label: 'Nord' },
  { id: 'one-dark', label: 'One Dark' },
  { id: 'one-light', label: 'One Light' },
  { id: 'pojoaque', label: 'Pojoaque' },
  { id: 'shades-of-purple', label: 'Shades Of Purple' },
  { id: 'solarized-dark-atom', label: 'Solarized Dark Atom' },
  { id: 'synthwave84', label: 'Synthwave84' },
  { id: 'vs', label: 'Vs' },
  { id: 'vsc-dark-plus', label: 'Vsc Dark Plus' },
  { id: 'xonokai', label: 'Xonokai' },
  { id: 'z-touch', label: 'Z Touch' },
  { id: 'catppuccin-latte', label: 'Catppuccin Latte' },
  { id: 'catppuccin-frappe', label: 'Catppuccin Frappe' },
  { id: 'catppuccin-macchiato', label: 'Catppuccin Macchiato' },
  { id: 'catppuccin-mocha', label: 'Catppuccin Mocha' },
];
