// AUTO-GENERATED by gen-prism.cjs - do not edit by hand.
// Prism theme CSS imported as strings (Vite ?inline) so we can swap the active
// theme at runtime by replacing the contents of a single <style> element.
// Switching is pure CSS - no re-highlighting of code blocks needed.
import theme_default from 'prismjs/themes/prism.css?inline';
import theme_okaidia from 'prismjs/themes/prism-okaidia.css?inline';
import theme_twilight from 'prismjs/themes/prism-twilight.css?inline';
import theme_solarizedlight from 'prismjs/themes/prism-solarizedlight.css?inline';
import theme_tomorrow from 'prismjs/themes/prism-tomorrow.css?inline';
import theme_a11y_dark from 'prism-themes/themes/prism-a11y-dark.css?inline';
import theme_atom_dark from 'prism-themes/themes/prism-atom-dark.css?inline';
import theme_base16_ateliersulphurpool_light from 'prism-themes/themes/prism-base16-ateliersulphurpool.light.css?inline';
import theme_cb from 'prism-themes/themes/prism-cb.css?inline';
import theme_coldark_cold from 'prism-themes/themes/prism-coldark-cold.css?inline';
import theme_coldark_dark from 'prism-themes/themes/prism-coldark-dark.css?inline';
import theme_coy_without_shadows from 'prism-themes/themes/prism-coy-without-shadows.css?inline';
import theme_darcula from 'prism-themes/themes/prism-darcula.css?inline';
import theme_dracula from 'prism-themes/themes/prism-dracula.css?inline';
import theme_duotone_dark from 'prism-themes/themes/prism-duotone-dark.css?inline';
import theme_duotone_earth from 'prism-themes/themes/prism-duotone-earth.css?inline';
import theme_duotone_forest from 'prism-themes/themes/prism-duotone-forest.css?inline';
import theme_duotone_light from 'prism-themes/themes/prism-duotone-light.css?inline';
import theme_duotone_sea from 'prism-themes/themes/prism-duotone-sea.css?inline';
import theme_duotone_space from 'prism-themes/themes/prism-duotone-space.css?inline';
import theme_ghcolors from 'prism-themes/themes/prism-ghcolors.css?inline';
import theme_gruvbox_dark from 'prism-themes/themes/prism-gruvbox-dark.css?inline';
import theme_gruvbox_light from 'prism-themes/themes/prism-gruvbox-light.css?inline';
import theme_holi_theme from 'prism-themes/themes/prism-holi-theme.css?inline';
import theme_hopscotch from 'prism-themes/themes/prism-hopscotch.css?inline';
import theme_lucario from 'prism-themes/themes/prism-lucario.css?inline';
import theme_material_dark from 'prism-themes/themes/prism-material-dark.css?inline';
import theme_material_light from 'prism-themes/themes/prism-material-light.css?inline';
import theme_material_oceanic from 'prism-themes/themes/prism-material-oceanic.css?inline';
import theme_night_owl from 'prism-themes/themes/prism-night-owl.css?inline';
import theme_nord from 'prism-themes/themes/prism-nord.css?inline';
import theme_one_dark from 'prism-themes/themes/prism-one-dark.css?inline';
import theme_one_light from 'prism-themes/themes/prism-one-light.css?inline';
import theme_pojoaque from 'prism-themes/themes/prism-pojoaque.css?inline';
import theme_shades_of_purple from 'prism-themes/themes/prism-shades-of-purple.css?inline';
import theme_solarized_dark_atom from 'prism-themes/themes/prism-solarized-dark-atom.css?inline';
import theme_synthwave84 from 'prism-themes/themes/prism-synthwave84.css?inline';
import theme_vs from 'prism-themes/themes/prism-vs.css?inline';
import theme_vsc_dark_plus from 'prism-themes/themes/prism-vsc-dark-plus.css?inline';
import theme_xonokai from 'prism-themes/themes/prism-xonokai.css?inline';
import theme_z_touch from 'prism-themes/themes/prism-z-touch.css?inline';
import theme_catppuccin_latte from './catppuccin-prism/latte.css?inline';
import theme_catppuccin_frappe from './catppuccin-prism/frappe.css?inline';
import theme_catppuccin_macchiato from './catppuccin-prism/macchiato.css?inline';
import theme_catppuccin_mocha from './catppuccin-prism/mocha.css?inline';

const PRISM_CSS: Record<string, string> = {
  'default': theme_default,
  'okaidia': theme_okaidia,
  'twilight': theme_twilight,
  'solarizedlight': theme_solarizedlight,
  'tomorrow': theme_tomorrow,
  'a11y-dark': theme_a11y_dark,
  'atom-dark': theme_atom_dark,
  'base16-ateliersulphurpool.light': theme_base16_ateliersulphurpool_light,
  'cb': theme_cb,
  'coldark-cold': theme_coldark_cold,
  'coldark-dark': theme_coldark_dark,
  'coy-without-shadows': theme_coy_without_shadows,
  'darcula': theme_darcula,
  'dracula': theme_dracula,
  'duotone-dark': theme_duotone_dark,
  'duotone-earth': theme_duotone_earth,
  'duotone-forest': theme_duotone_forest,
  'duotone-light': theme_duotone_light,
  'duotone-sea': theme_duotone_sea,
  'duotone-space': theme_duotone_space,
  'ghcolors': theme_ghcolors,
  'gruvbox-dark': theme_gruvbox_dark,
  'gruvbox-light': theme_gruvbox_light,
  'holi-theme': theme_holi_theme,
  'hopscotch': theme_hopscotch,
  'lucario': theme_lucario,
  'material-dark': theme_material_dark,
  'material-light': theme_material_light,
  'material-oceanic': theme_material_oceanic,
  'night-owl': theme_night_owl,
  'nord': theme_nord,
  'one-dark': theme_one_dark,
  'one-light': theme_one_light,
  'pojoaque': theme_pojoaque,
  'shades-of-purple': theme_shades_of_purple,
  'solarized-dark-atom': theme_solarized_dark_atom,
  'synthwave84': theme_synthwave84,
  'vs': theme_vs,
  'vsc-dark-plus': theme_vsc_dark_plus,
  'xonokai': theme_xonokai,
  'z-touch': theme_z_touch,
  'catppuccin-latte': theme_catppuccin_latte,
  'catppuccin-frappe': theme_catppuccin_frappe,
  'catppuccin-macchiato': theme_catppuccin_macchiato,
  'catppuccin-mocha': theme_catppuccin_mocha,
};

export function applyPrismTheme(id: string): void {
  const css = PRISM_CSS[id] ?? PRISM_CSS.default;
  let style = document.getElementById('prism-theme') as HTMLStyleElement | null;
  if (!style) {
    style = document.createElement('style');
    style.id = 'prism-theme';
    document.head.appendChild(style);
  }
  style.textContent = css;
}
